### ISSUE TITLE
Exported name "TippyComponent" not provided

### ISSUE THREAD

**Issue by bart** [timb-103/nuxt-emoji#2]
Hi,

when I try to use this package in a Nuxt project I'm getting the following error as soon as I add it to a template: `Uncaught SyntaxError: The requested module '/_nuxt/node_modules/vue-tippy/dist/vue-tippy.esm-browser.js?v=1bf4bf49' does not provide an export named 'TippyComponent' (at NuxtEmoji.vue:71:10)`

I created a simple example: https://github.com/bart/test-nuxt-emoji
You can see the error in dev console.

Any idea what the reason could be and how to solve it?

Thanks in advance and kind regards.

**Comment by bart** [comment]
@timb-103 Any idea?

**Comment by bart** [comment]
In case anyone else is facing this issue: I created a patch (postinstall `patch-package`):

```
// /patches/nuxt-emoji+1.0.1.patch
diff --git a/node_modules/nuxt-emoji/components/NuxtEmoji.vue b/node_modules/nuxt-emoji/components/NuxtEmoji.vue
index 33665e1..153f1c0 100644
--- a/node_modules/nuxt-emoji/components/NuxtEmoji.vue
+++ b/node_modules/nuxt-emoji/components/NuxtEmoji.vue
@@ -68,7 +68,7 @@

 <script setup lang="ts">
 import EmojisList from '../assets/emojis'
-import { TippyComponent } from 'vue-tippy'
+import { Tippy } from 'vue-tippy'
 import type { Placement } from '@popperjs/core'

 defineProps({
@@ -99,7 +99,7 @@ const emits = defineEmits(['onSelect'])
 const filter = ref('')
 const emojis = ref<Emojis>(EmojisList)
 const activeGroup = ref('Smileys & People')
-const tippyInstance = ref<TippyComponent>()
+const tippyInstance = ref<Tippy>()
 const filtered = ref<Partial<Emoji>[]>()

 /**
```

Cheers!

**Comment by timb-103** [comment]
If you want to open a PR, happy to merge it :)
